module.exports = {
  future: {
    removeDeprecatedGapUtilities: true,
  },
  purge: [
    './public/**/*.html',
    './public/**/*.js',
    './api/**/*.tsx',
    './components/**/*.tsx',
    './sections/**/*.tsx',
    './pages/**/*.tsx',
  ],
  theme: {
    fontFamily: {
      sans: [
        'system',
        '-apple-system',
        '\\.SFNSText-Regular',
        'San\\ Francisco',
        'Roboto',
        'Segoe\\ UI',
        'Helvetica\\ Neue',
        'Lucida\\ Grande',
        'sans-serif',
        'Apple\\ Color\\ Emoji',
        'Segoe\\ UI\\ Emoji',
        'Segoe\\ UI\\ Symbol',
      ],
      serif: [
        'Palatino\\ Linotype',
        'Palatino',
        'Palladio',
        'URW\\ Palladio\\ L',
        'Book\\ Antiqua',
        'Baskerville',
        'Bookman\\ Old\\ Style',
        'Bitstream\\ Charter',
        'Nimbus\\ Roman\\ No9\\ L',
        'Garamond',
        'Apple\\ Garamond',
        'ITC\\ Garamond Narrow',
        'New\\ Century\\ Schoolbook',
        'Century\\ Schoolbook',
        'Century\\ Schoolbook L',
        'Georgia',
        'serif',
        'Apple\\ Color\\ Emoji',
        'Segoe\\ UI\\ Emoji',
        'Segoe\\ UI\\ Symbol',
      ],
      mono: [
        'Hack',
        'DejaVu\\ Sans\\ Mono',
        'Source\\ Code Pro',
        'Fira\\ Code',
        'Space\\ Mono',
        'Droid\\ Sans Mono',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        'Liberation\\ Mono',
        'Courier\\ New',
        'monospace',
        'Apple\\ Color\\ Emoji',
        'Segoe\\ UI\\ Emoji',
        'Segoe\\ UI\\ Symbol',
      ],
    },
  },
  variants: {},
  plugins: [],
}
